export enum OrmModel {
  USER_MODEL = 'USER_MODEL',
  ROLE_MODEL = 'ROLE_MODEL',
  SESSION_MODEL = 'SESSION_MODEL',
  USER_QUIZZES_MODEL = 'USER_QUIZZES_MODEL',
  PASSWORD_RECOVERY_MODEL = 'PASSWORD_RECOVERY_MODEL',
}
